[project]
name = "law-tool-kor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "langchain-mcp-adapters==0.0.9",
    "mcp>=1.6.0",
]
